# Generated by Django 3.2.5 on 2022-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='candidate_profile/'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default-image.png', null=True, upload_to='project_image/'),
        ),
    ]
