# Generated by Django 3.2.5 on 2022-05-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created',
        ),
    ]
