# Generated by Django 3.2.5 on 2022-05-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
