# Generated by Django 3.2.5 on 2022-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220515_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
